function formatarMensagemCDV(dados) {
  const n = '\n';
  const origem     = dados.origem || '';
  const destino    = dados.destino || '';
  const pontos     = dados.pontos || '0';
  const programa   = dados.programa || '';
  const cia        = dados.cia || '';
  const cabine     = dados.cabine || 'Econômica';
  const tipoVoo    = dados.tipoVoo || 'internacional';
  const datasIda   = dados.datasIda || '—';
  const datasVolta = dados.datasVolta || '—';
  const cpm        = PROGRAMAS_CPM[programa] || 0;
  const milhasNum  = parseInt(String(pontos).replace(/[^0-9]/g, '')) || 0;
  const valorReais = cpm > 0 ? Math.round((milhasNum / 1000) * cpm) : 0;
  const valorStr   = valorReais > 0 ? 'R$ ' + valorReais.toLocaleString('pt-BR') : '—';
  const linkProg   = PROGRAMAS_LINK[programa] || '';
  const trechoInfo = tipoVoo === 'internacional' ? ' o trecho em ' + cabine : '';
  const pontosFormatado = milhasNum > 0 ? milhasNum.toLocaleString('pt-BR') : pontos;
  let msg = '';
  msg += '*' + origem + ' - ' + destino + ' por ' + pontosFormatado + ' pontos OU ' + valorStr + trechoInfo + '*' + n + n;
  msg += RODAPE_MILHAS + n + n;
  msg += 'Você pode comprar essa passagem no Balcão de Milhas CDV por aproximadamente ' + valorStr + ' o trecho + taxa de embarque.' + n + n;
  msg += BALCAO_LINK + n + n;
  msg += '🛫 *DATAS DE IDA*' + n + datasIda + n + n;
  msg += '🛬 *DATAS DE VOLTA*' + n + datasVolta + n + n;
  msg += '🎟️ *PROGRAMA* ' + programa + n + n;
  msg += '✈️ *CIA AÉREA* ' + cia + n + n;
  msg += '🔗 *LINK* ' + linkProg + n + n;
  msg += RODAPE_MILHAS;
  return msg;
}
